linux-user: use common Makefile.inc

diff --git a/linux-user/vmcall/Makefile b/linux-user/vmcall/Makefile
--- a/linux-user/vmcall/Makefile
+++ b/linux-user/vmcall/Makefile
@@ -1,47 +1,47 @@
-NYX_INCLUDE_PATH ?= $(EXAMPLES_ROOT)
-KERNEL_IMAGE ?= /boot/vmlinuz-$$(uname -r)
-SHAREDIR ?= $$PWD/sharedir
-KAFL_WORKDIR=$$(dynaconf -i kafl_fuzzer.common.config.settings get work_dir)
-
 all: debug
 
-LIBNYX_AGENT_ROOT ?= $(EXAMPLES_ROOT)/linux-user/libnyx_agent
+include ../Makefile.inc
 include $(LIBNYX_AGENT_ROOT)/Makefile.inc
 
-CFLAGS += -g -O0 -I$(NYX_INCLUDE_PATH) -I$(LIBNYX_AGENT_INCLUDE)
-LIBS += $(LIBNYX_AGENT_STATIC)
+KERNEL_IMAGE ?= /boot/vmlinuz-$$(uname -r)
+SHAREDIR ?= $$PWD/sharedir
 
+TARGET=vmcall
+
+CFLAGS += -Wall -I$(NYX_INCLUDE_PATH) -I$(LIBNYX_AGENT_INCLUDE)
+LIBS += $(LIBNYX_AGENT_STATIC)
 
 release: static
 
 static: CFLAGS += -static -O2
-static: vmcall
+static: $(TARGET)
 
-debug: CFLAGS += -DDEBUG -Og
-debug: vmcall
+debug: CFLAGS += -g -O0 -DDEBUG
+debug: $(TARGET)
 
-asan: CFLAGS += -fsanitize=address,undefined -DDEBUG
-asan: vmcall
+asan: CFLAGS += -g -O0 -DDEBUG -fsanitize=address,undefined
+asan: $(TARGET)
 
-vmcall: $(LIBNYX_AGENT_BUILD)
-vmcall: src/vmcall.c
+$(TARGET): $(LIBNYX_AGENT_BUILD)
+$(TARGET): src/$(TARGET).c
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LIBS)
 
-vmcall.cpio.gz: vmcall
+$(TARGET).cpio.gz: $(TARGET)
 	../scripts/gen_initrd.sh $@ $^
 
-run: vmcall.cpio.gz
+run: $(TARGET).cpio.gz
 	@# default kAFL config enables Linux serial console, see $$KAFL_WORK_DIR/serial_00.log
 	kafl fuzz \
 		--kernel $(KERNEL_IMAGE) \
 		--initrd $< \
+		--memory 512 \
 		--sharedir $(SHAREDIR) \
 		--purge -v --log
 
 test:
 	$(MAKE) clean
 	$(MAKE) debug
-	$(MAKE) vmcall.cpio.gz
+	$(MAKE) $(TARGET).cpio.gz
 	@mkdir testshare
 	@dd if=/dev/random bs=1k count=1024 of=testshare/test_1M.bin
 	@dd if=/dev/random bs=1k count=2048 of=testshare/test_2M.bin
@@ -53,12 +53,12 @@ test:
 	@cd testshare && md5sum test_*bin > test_md5sums
 	@cp test_agent.sh testshare/agent.sh
 	SHAREDIR=$$PWD/testshare $(MAKE) run
-	@cp testshare/test_md5sums $(KAFL_WORKDIR)/dump/test_md5sums
-	@cd $(KAFL_WORKDIR)/dump/ && md5sum -c test_md5sums || echo "hpush/hget fail!"
-	@test $$(grep -c foobar $(KAFL_WORKDIR)/dump/foo) -eq 3 || echo "hcat fail!"
+	@cp testshare/test_md5sums $(KAFL_WORK_DIR)/dump/test_md5sums
+	@cd $(KAFL_WORK_DIR)/dump/ && md5sum -c test_md5sums || echo "hpush/hget fail!"
+	@test $$(grep -c foobar $(KAFL_WORK_DIR)/dump/foo) -eq 3 || echo "hcat fail!"
 
 clean:
-	rm -f vmcall
+	rm -f $(TARGET) $(TARGET).cpio.gz
 	rm -rf testshare
 
 tags:
